name: lend_lab
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/splash_screen.png
    - lib/assets/images/login_auth_screen.png
    - lib/assets/images/signup_auth_screen.png
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
