-- LendLab public schema restore for Supabase SQL Editor.
-- Paste this whole file into Supabase Dashboard > SQL Editor > Run.
--
-- Notes:
-- - This intentionally skips Supabase-managed schemas/roles such as auth,
--   storage, realtime, anon, authenticated, and service_role.
-- - This script drops and recreates only public."Pinjaman" and public."User".
-- - The app currently uses the anon key directly, so broad grants are included
--   to match the old project behavior.

begin;

drop table if exists public."Pinjaman" cascade;
drop table if exists public."User" cascade;

create table public."User" (
  id_user integer generated by default as identity primary key,
  first_name varchar(50),
  last_name varchar(50),
  email varchar(255) not null unique,
  password varchar(255) not null,
  session_token varchar(255)
);

create table public."Pinjaman" (
  id_pinjaman integer generated by default as identity primary key,
  id_user integer default 1 references public."User"(id_user),
  nama_peminjam varchar(50),
  kategori varchar(50),
  nilai varchar(255),
  tanggal_meminjam timestamp without time zone default now(),
  tanggal_pengembalian timestamp without time zone,
  selesai boolean default false not null
);

insert into public."User"
  (id_user, first_name, last_name, email, password, session_token)
values
  (2, 'Rafu', 'Mazta', 'rafumazta@gmail.com', 'rafu12345', null),
  (3, 'Wak Abdul', 'Sungai Musi', 'buayaputihsungaimusi@gmail.com', 'apsijir123', null),
  (4, 'test', 'test', 'test@test.test', 'test', null),
  (5, 'a', 'a', 'a', 'a', null),
  (6, 'test', 'kedua kalinya', 'test2kali@example.com', 'test12345', null),
  (7, 'nabila', 'dinda', 'nabiladinda912@gmail.com', 'dinda0608', null),
  (11, 'Nanda', 'Putri', 'nandaaputr07@gmail.com', 'tukangturu00', null),
  (12, 'Nabils', 'nda', 'nabiladinda', 'asddad', null),
  (1, 'Guest', 'Guest', 'guest@test.com', '123456', null),
  (13, 'Jumiati', 'Sadiah', 'miasadiah6@gmail.com', '123456', null),
  (14, 'Tes', 'Di Android', 'tesandroid@gmail.com', '123456', null),
  (15, 'Rusdi', 'Aren', 'rusdiemut@booloe.com', 'kamalasu', null),
  (16, 'tes', 'hhhhbb', 'tes@email.com', '99999999', null),
  (20, 'Alifah', 'Salsabillah', 'alifahsalsa11@gmail.com', 'www123iop', null),
  (22, 'Rusdi', 'Lagi', 'rusdimut@booloe.com', '12345678', null),
  (25, 'g', 'b', 'gnovfitriana@gmail.com', '123456', null),
  (27, 'kodrat', 'coc', 'kodratcoc@gmail.com', 'kodrat12345', null);

insert into public."Pinjaman"
  (id_pinjaman, id_user, nama_peminjam, kategori, nilai, tanggal_meminjam, tanggal_pengembalian, selesai)
values
  (7, 1, 'Pak Asep', 'barang', 'Celana Mas Mursyid', '2023-12-07 02:36:09', null, false),
  (8, 1, 'Fuad 12 nyapu di "Kebun Raya Bogor"', 'uang', '15500', '2023-12-06 19:37:48.517767', '2023-12-09 23:12:40', true),
  (4, 1, 'Wak Abdul Sungai Musi', 'uang', '110000', '2023-12-07 00:00:00', '2023-12-09 23:13:38.349453', true),
  (5, 1, 'Mas Amba', 'barang', 'Handuk Mas Fuad', '2023-12-07 02:35:08', '2023-12-10 00:11:54.807357', true),
  (3, 1, 'Pace Kanaeru', 'uang', '25000', '2023-12-07 00:00:00', null, false),
  (14, 1, 'awewafhfgh', 'uang', '1234', '2023-06-30 00:00:00', null, false),
  (2, 1, 'Yanto "Pasuruan" gempa bumi', 'uang', '50000', '2023-08-31 00:00:00', null, false),
  (6, 1, 'Mas Rusdi', 'barang', 'Baju Si Imut 2', '2023-09-28 00:00:00', null, false),
  (9, 2, 'Irfan', 'uang', '1000000', '2023-11-03 00:00:00', '2023-12-10 00:53:23.004376', true),
  (16, 15, 'Ilham', 'barang', 'semvak naik bolong depan', '1900-12-10 00:00:00', null, false),
  (17, 15, 'Dimas', 'uang', '27000000000000000', '1900-12-05 00:00:00', null, false),
  (18, 16, 'ucok', 'barang', 'sertifikat tanah kebun sawit 10 hektar', '2023-12-10 00:00:00', null, false),
  (19, 16, 'ucok', 'uang', '10000000000000000000', '2023-12-10 00:00:00', null, false),
  (20, 20, 'pipo', 'barang', 'action figur', '2023-12-07 00:00:00', '2023-12-10 08:07:05.442739', true),
  (21, 7, 'Lela', 'barang', 'Baju', '2023-12-05 00:00:00', '2023-12-10 10:40:41.278169', true),
  (12, 2, 'Raflyansyah', 'uang', '50000342', '2023-09-27 00:00:00', '2023-12-12 04:52:30.593341', true),
  (15, 2, 'Aqil', 'uang', '30000', '2023-12-10 00:00:00', '2023-12-12 04:52:33.204946', true),
  (10, 2, 'Taryono', 'barang', 'Buku Gambar', '2023-09-21 00:00:00', '2023-12-12 04:52:35.89294', true),
  (11, 2, 'Fuad', 'barang', 'Celana', '2023-09-21 00:00:00', '2023-12-12 04:52:38.120988', true),
  (22, 2, 'Ilal', 'uang', '2000', '2023-12-12 00:00:00', '2023-12-12 04:57:26.035153', true),
  (24, 7, 'juni', 'uang', '10000', '2023-12-11 00:00:00', '2023-12-13 13:46:09.18907', true),
  (25, 7, 'Meri', 'barang', 'Charger HP', '2023-12-05 00:00:00', '2023-12-13 13:46:43.070609', true),
  (26, 11, 'Salsa', 'barang', 'Kandang Harimau', '2023-12-14 00:00:00', null, false),
  (27, 11, 'Obama', 'barang', 'Vespa', '2023-12-14 00:00:00', null, false),
  (13, 11, 'Megatron', 'uang', '60000', '2023-12-09 00:00:00', '2023-12-14 00:53:37.237', true),
  (28, 11, 'Sumanto', 'uang', '2250000', '2023-12-14 00:00:00', '2023-12-14 13:44:11.384', true),
  (29, 11, 'Bobi', 'uang', '12000', '2023-12-07 00:00:00', null, false),
  (31, 13, 'Susi', 'barang', 'Buku Gambar', '2023-12-19 00:00:00', null, false),
  (30, 13, 'Mimi', 'uang', '10000', '2023-12-03 00:00:00', '2023-12-19 21:20:23.480177', true),
  (32, 7, 'anne', 'uang', '50000', '2023-12-14 00:00:00', null, false),
  (33, 25, 'gg', 'uang', '1500000', '2023-12-20 00:00:00', '2023-12-20 16:58:39.427143', true),
  (35, 20, 'pipo', 'uang', '120000', '2023-12-13 00:00:00', '2023-12-20 19:30:06.563116', true),
  (36, 20, 'yupi', 'barang', 'kuku palsu', '2023-12-01 00:00:00', null, false),
  (37, 11, 'Nabila', 'barang', 'Mangkok Bubur Ayam', '2023-12-17 00:00:00', null, false),
  (38, 11, 'Datuk', 'uang', '5000', '2023-12-18 00:00:00', null, false),
  (39, 11, 'Nabila', 'barang', 'Kotak nasi lazatto', '2023-12-17 00:00:00', null, false),
  (34, 25, 'bulan', 'barang', 'Laptop', '2023-12-20 00:00:00', '2023-12-20 22:23:50.2864', true),
  (40, 25, 'pakYudi', 'uang', '1500000', '2023-12-20 00:00:00', '2023-12-20 22:25:53.791104', true),
  (41, 25, 'y', 'barang', 'Charger HP', '2023-12-09 00:00:00', '2023-12-20 22:27:33.672951', true),
  (42, 25, 'y', 'barang', 'Baju', '2023-12-03 00:00:00', '2023-12-21 10:55:25.921917', true),
  (23, 2, 'Ilal', 'uang', '2000', '2023-12-12 00:00:00', '2024-07-01 10:55:41.49', true),
  (44, 2, 'PakBudi', 'barang', 'Botol Minum', '2024-07-01 00:00:00', null, false),
  (43, 2, 'PakBudi', 'uang', '100000', '2024-07-01 00:00:00', '2024-07-01 13:07:26.57', true);

select setval(pg_get_serial_sequence('public."User"', 'id_user'), 27, true);
select setval(pg_get_serial_sequence('public."Pinjaman"', 'id_pinjaman'), 44, true);

grant usage on schema public to anon, authenticated, service_role;
grant all on table public."User" to anon, authenticated, service_role;
grant all on table public."Pinjaman" to anon, authenticated, service_role;
grant all on sequence public."User_id_user_seq" to anon, authenticated, service_role;
grant all on sequence public."Pinjaman_id_pinjaman_seq" to anon, authenticated, service_role;

-- Keep RLS disabled to match the original app's anon-key CRUD behavior.
alter table public."User" disable row level security;
alter table public."Pinjaman" disable row level security;

-- Optional realtime publication. Ignore errors if publication already has the table.
do $$
begin
  begin
    alter publication supabase_realtime add table public."User";
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;

  begin
    alter publication supabase_realtime add table public."Pinjaman";
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;
end $$;

commit;

